
homeassistant:

group:
  usfl_start:
    name: USFL Game Start
    entities:
      - calendar.usfl_new_jersey_generals
      - calendar.usfl_new_orleans_breakers
      - calendar.usfl_michigan_panthers
      - calendar.usfl_philadelphia_stars
      - calendar.usfl_houston_gamblers
      - calendar.usfl_tampa_bay_bandits
      - calendar.usfl_pittsburgh_maulers
      - calendar.usfl_birmingham_stallions
