homeassistant:

# USFL Team Sensor
# team_id: 7
# name: 'USFL Memphis Showboats'

#################################################################
#                                                               #
#                       Template Sensors                        #
#                                                               #
#################################################################

template:

  - sensor:
      - unique_id: usfl_memphis_showboats
        state: >
                {{ states('calendar.usfl_memphis_showboats') }}
        picture: https://i.imgur.com/zbsMrZw.png
        attributes:
            friendly_name: "Memphis Showboats"
            abbrev: TB
            logo: https://i.imgur.com/zbsMrZw.png
            conference: South
            next_game: >
                {{ as_datetime(state_attr('calendar.usfl_memphis_showboats','start_time')) }}

  - binary_sensor:
      - unique_id: usfl_memphis_showboats_game_day
        state: >
          {% set today_string = states('sensor.date')  %}
          {% set next_game = as_timestamp(state_attr('calendar.usfl_memphis_showboats','start_time'), default=0) | timestamp_custom("%Y-%m-%d") %}
          {% if next_game == today_string %}
          True
          {% endif %}
        attributes:
            friendly_name: "Memphis Showboats Game Day"
