homeassistant:

# USFL Team Sensor
# team_id: 4
# name: 'USFL New Orleans Breakers'

#################################################################
#                                                               #
#                       Template Sensors                        #
#                                                               #
#################################################################

template:

  - sensor:
      - unique_id: usfl_new_orleans_breakers
        state: NO
        picture: https://i.imgur.com/NmTVzV6.png
        attributes:
            friendly_name: "New Orleans Breakers"
            abbrev: NO
            logo: https://i.imgur.com/mVCJlir.png
            conference: South
            next_game: >
                {{ as_datetime(state_attr('calendar.usfl_new_orleans_breakers','start_time') | float(0)) }}

  - binary_sensor:
      - unique_id: usfl_new_orleans_breakers_game_day
        state: >
          {% set today_string = states('sensor.date')  %}
          {% set next_game = as_timestamp(state_attr('calendar.usfl_new_orleans_breakers','start_time'), default=0) | timestamp_custom("%Y-%m-%d") %}
          {% if next_game == today_string %}
          True
          {% endif %}
        attributes:
            friendly_name: "New Orleans Breakers Game Day"
