homeassistant:

# USFL Team Sensor
# team_id: 3
# name: 'USFL New Jersey Generals'

#################################################################
#                                                               #
#                       Template Sensors                        #
#                                                               #
#################################################################

template:

  - sensor:
      - unique_id: usfl_new_jersey_generals
        state: NJ
        picture: https://i.imgur.com/5ivBGek.png
        attributes:
            friendly_name: "New Jersey Generals"
            abbrev: NJ
            logo: https://i.imgur.com/R9UOOoM.png
            conference: North
            next_game: >
                {{ as_datetime(state_attr('calendar.usfl_new_jersey_generals','start_time')) }}

  - binary_sensor:
      - unique_id: usfl_new_jersey_generals_game_day
        state: >
          {% set today_string = states('sensor.date')  %}
          {% set next_game = as_timestamp(state_attr('calendar.usfl_new_jersey_generals','start_time'), default=0) | timestamp_custom("%Y-%m-%d") %}
          {% if next_game == today_string %}
          True
          {% endif %}
        attributes:
            friendly_name: "New Jersey Generals Game Day"
