
homeassistant:

# USFL Team Sensor
# team_id: 5
# name: 'USFL Philadelphia Stars'

#################################################################
#                                                               #
#                       Template Sensors                        #
#                                                               #
#################################################################

template:

  - sensor:
      - unique_id: usfl_philadelphia_stars
        state: PHI
        picture: https://i.imgur.com/GH9LvhM.png
        attributes:
            friendly_name: "Philadelphia Stars"
            abbrev: PHI
            logo: https://i.imgur.com/9afGCyA.png
            conference: North
            next_game: >
                {{ as_datetime(state_attr('calendar.usfl_philadelphia_stars','start_time')) }}

  - binary_sensor:
      - unique_id: usfl_philadelphia_stars_game_day
        state: >
          {% set today_string = states('sensor.date')  %}
          {% set next_game = as_timestamp(state_attr('calendar.usfl_philadelphia_stars','start_time')), "%Y-%m-%d") | timestamp_custom("%Y-%m-%d") %}
          {% if next_game == today_string %}
          True
          {% endif %}
        attributes:
            friendly_name: "Philadelphia Stars Game Day"
